package:
        name: molsimplify
        version: "1.6.0"
source:
        git_url: https://github.com/hjkgrp/molSimplify.git
        git_tag: master
build:
        number: 1
        preserve_egg_dir: True
requirements:
 build:
        - python=3.6.8
        - setuptools
 run:
        - scipy
        - openbabel
        - setuptools
        - pandas
        - python=3.6.8
        - numpy
        - scikit-learn
about:
        home: https://github.com/hjkgrp/molSimplify
        license: BSD
