package:
        name: molsimplify
        version: "1.2.8"
source:
        git_url: https://github.com/hjkgrp/molSimplify.git
        git_tag: JP
build:
        number: 1
        preserve_egg_dir: True
requirements:
 build:
        - python
        - setuptools
 run:
        - openbabel
        - setuptools
        - python
        - numpy
        - scipy 
about:
        home: https://github.com/hjkgrp/molSimplify
        license: BSD
