package:
        name: molsimplify
        version: "1.7.1" # change this when a new version of molSimplify is released on GitHub
source:
        # git_url: https://github.com/hjkgrp/molSimplify.git
        # git_tag: master
        path : ../molSimplify
build:
        number: 1
        preserve_egg_dir: True
requirements:
 build:
        - python=3.7
        - setuptools
 run:
        - python=3.7
        - setuptools
        - openbabel
        - xtb
        - psi4
        - tensorflow
        - keras
        - pytorch
        - pyqt
        - pip
        - qt
        - scikit-learn
        - pandas
        - scipy
        - pymongo
        - iodata
        - libffi
about:
        home: https://github.com/hjkgrp/molSimplify
        license: BSD
