package:
        name: molsimplify
        version: "1.7.4" # change this when a new version of molSimplify is released on GitHub
source:
        # git_url: https://github.com/hjkgrp/molSimplify.git
        # git_tag: master
        path : ../molSimplify # Assumes the cloned, up-to-date molSimplify repo is in the parent folder of meta.yaml
build:
        number: 1
        preserve_egg_dir: True
requirements:
 build:
        - python=3.10
        - setuptools
 run:
        - python=3.10
        - openbabel
        - tensorflow-base >2.0
        - scikit-learn
        - pyyaml
        - pandas
        - scipy
        - libffi
        - networkx >=2.7
        - importlib_resources
        - pip
        - matplotlib
        - pymongo
        - beautifulsoup4
        - theochem::iodata
        - xtb
        - scikit-image
about:
        home: https://github.com/hjkgrp/molSimplify
        license: BSD
